"""Initial schema

Revision ID: 1bd6805544d1
Revises: 
Create Date: 2026-08-26 13:42:36.697531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1bd6805544d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation_setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installation_setting'))
    )
    with op.batch_alter_table('installation_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installation_setting_key'), ['key'], unique=True)

    op.create_table('organization',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('brand_primary', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization'))
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_slug'), ['slug'], unique=True)

    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_key', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('category',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_category_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('org_id', 'slug', name='uq_category_org_slug')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_org_id'), ['org_id'], unique=False)

    op.create_table('discussion_flag',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_discussion_flag_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_discussion_flag_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion_flag'))
    )
    with op.batch_alter_table('discussion_flag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_flag_org_id'), ['org_id'], unique=False)

    op.create_table('discussion_group',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_discussion_group_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion_group')),
    sa.UniqueConstraint('org_id', 'slug', name='uq_discussion_group_org_slug')
    )
    with op.batch_alter_table('discussion_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_group_org_id'), ['org_id'], unique=False)

    op.create_table('discussion_reaction',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_discussion_reaction_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_discussion_reaction_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion_reaction')),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', 'emoji', name='uq_discussion_reaction_user_target')
    )
    with op.batch_alter_table('discussion_reaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_reaction_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_discussion_reaction_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_reaction_user_id'), ['user_id'], unique=False)

    op.create_table('glossary_v1_term',
    sa.Column('term', sa.String(length=100), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_glossary_v1_term_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_glossary_v1_term_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_glossary_v1_term_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary_v1_term')),
    sa.UniqueConstraint('org_id', 'term', name='uq_glossary_v1_term_org')
    )
    with op.batch_alter_table('glossary_v1_term', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glossary_v1_term_org_id'), ['org_id'], unique=False)

    op.create_table('invitation',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['user.id'], name=op.f('fk_invitation_accepted_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_invitation_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_invitation_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_invitation_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitation'))
    )
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitation_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitation_token_hash'), ['token_hash'], unique=True)

    op.create_table('job',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_job_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index('ix_job_claim', ['status', 'run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_status'), ['status'], unique=False)

    op.create_table('membership',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_membership_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_membership_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership')),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_membership_user_org')
    )
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_user_id'), ['user_id'], unique=False)

    op.create_table('notification',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_notification_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notification_user_read', ['user_id', 'read_at'], unique=False)

    op.create_table('org_domain',
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_org_domain_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_domain'))
    )
    with op.batch_alter_table('org_domain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_domain_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_org_domain_org_id'), ['org_id'], unique=False)

    op.create_table('org_plugin',
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('plugin_slug', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('upgraded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_org_plugin_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_plugin')),
    sa.UniqueConstraint('org_id', 'plugin_slug', name='uq_org_plugin')
    )
    with op.batch_alter_table('org_plugin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_plugin_org_id'), ['org_id'], unique=False)

    op.create_table('subscriber',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_subscriber_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriber')),
    sa.UniqueConstraint('org_id', 'email', name='uq_subscriber_org_email')
    )
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriber_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriber_token'), ['token'], unique=True)

    op.create_table('upload',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('has_variants', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_upload_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_upload_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_upload_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload')),
    sa.UniqueConstraint('key', name=op.f('uq_upload_key'))
    )
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_org_id'), ['org_id'], unique=False)

    op.create_table('content',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('featured_upload_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('template', sa.String(length=50), nullable=True),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.String(length=300), nullable=True),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_content_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['featured_upload_id'], ['upload.id'], name=op.f('fk_content_featured_upload_id_upload'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_content_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_content_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content')),
    sa.UniqueConstraint('org_id', 'type', 'slug', name='uq_content_org_type_slug')
    )
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_content_org_type_status', ['org_id', 'type', 'status'], unique=False)

    op.create_table('discussion_post',
    sa.Column('group_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_discussion_post_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['discussion_group.id'], name=op.f('fk_discussion_post_group_id_discussion_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_discussion_post_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_discussion_post_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion_post'))
    )
    with op.batch_alter_table('discussion_post', schema=None) as batch_op:
        batch_op.create_index('ix_discussion_post_group_activity', ['group_id', 'last_activity_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_post_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_post_org_id'), ['org_id'], unique=False)

    op.create_table('content_category',
    sa.Column('content_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_content_category_category_id_category'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name=op.f('fk_content_category_content_id_content'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'category_id', name=op.f('pk_content_category'))
    )
    op.create_table('discussion_follow',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_discussion_follow_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['discussion_post.id'], name=op.f('fk_discussion_follow_post_id_discussion_post'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_discussion_follow_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion_follow')),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_discussion_follow_user_post')
    )
    with op.batch_alter_table('discussion_follow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_follow_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_follow_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_follow_user_id'), ['user_id'], unique=False)

    op.create_table('discussion_reply',
    sa.Column('post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_discussion_reply_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_discussion_reply_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['discussion_reply.id'], name=op.f('fk_discussion_reply_parent_id_discussion_reply'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['discussion_post.id'], name=op.f('fk_discussion_reply_post_id_discussion_post'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_discussion_reply_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion_reply'))
    )
    with op.batch_alter_table('discussion_reply', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_reply_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_reply_post_id'), ['post_id'], unique=False)

    op.create_table('navigation_item',
    sa.Column('menu', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('content_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name=op.f('fk_navigation_item_content_id_content'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_navigation_item_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['navigation_item.id'], name=op.f('fk_navigation_item_parent_id_navigation_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_navigation_item'))
    )
    with op.batch_alter_table('navigation_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_navigation_item_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_navigation_item_org_menu', ['org_id', 'menu', 'position'], unique=False)

    op.create_table('newsletter_delivery',
    sa.Column('content_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('recipients_total', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name=op.f('fk_newsletter_delivery_content_id_content'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_newsletter_delivery_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_newsletter_delivery_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_newsletter_delivery_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_delivery'))
    )
    with op.batch_alter_table('newsletter_delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_delivery_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_newsletter_delivery_org_id'), ['org_id'], unique=False)

    op.create_table('newsletter_delivery_recipient',
    sa.Column('delivery_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('subscriber_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['newsletter_delivery.id'], name=op.f('fk_newsletter_delivery_recipient_delivery_id_newsletter_delivery'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_newsletter_delivery_recipient_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscriber.id'], name=op.f('fk_newsletter_delivery_recipient_subscriber_id_subscriber'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_delivery_recipient')),
    sa.UniqueConstraint('delivery_id', 'subscriber_id', name='uq_delivery_recipient')
    )
    with op.batch_alter_table('newsletter_delivery_recipient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_delivery_recipient_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_newsletter_delivery_recipient_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_delivery_recipient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_delivery_recipient_org_id'))
        batch_op.drop_index(batch_op.f('ix_newsletter_delivery_recipient_delivery_id'))

    op.drop_table('newsletter_delivery_recipient')
    with op.batch_alter_table('newsletter_delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_delivery_org_id'))
        batch_op.drop_index(batch_op.f('ix_newsletter_delivery_content_id'))

    op.drop_table('newsletter_delivery')
    with op.batch_alter_table('navigation_item', schema=None) as batch_op:
        batch_op.drop_index('ix_navigation_item_org_menu')
        batch_op.drop_index(batch_op.f('ix_navigation_item_org_id'))

    op.drop_table('navigation_item')
    with op.batch_alter_table('discussion_reply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_reply_post_id'))
        batch_op.drop_index(batch_op.f('ix_discussion_reply_org_id'))

    op.drop_table('discussion_reply')
    with op.batch_alter_table('discussion_follow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_follow_user_id'))
        batch_op.drop_index(batch_op.f('ix_discussion_follow_post_id'))
        batch_op.drop_index(batch_op.f('ix_discussion_follow_org_id'))

    op.drop_table('discussion_follow')
    op.drop_table('content_category')
    with op.batch_alter_table('discussion_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_post_org_id'))
        batch_op.drop_index(batch_op.f('ix_discussion_post_group_id'))
        batch_op.drop_index('ix_discussion_post_group_activity')

    op.drop_table('discussion_post')
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index('ix_content_org_type_status')
        batch_op.drop_index(batch_op.f('ix_content_org_id'))

    op.drop_table('content')
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_org_id'))

    op.drop_table('upload')
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriber_token'))
        batch_op.drop_index(batch_op.f('ix_subscriber_org_id'))

    op.drop_table('subscriber')
    with op.batch_alter_table('org_plugin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_plugin_org_id'))

    op.drop_table('org_plugin')
    with op.batch_alter_table('org_domain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_domain_org_id'))
        batch_op.drop_index(batch_op.f('ix_org_domain_domain'))

    op.drop_table('org_domain')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_user_read')
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_org_id'))

    op.drop_table('notification')
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_user_id'))
        batch_op.drop_index(batch_op.f('ix_membership_org_id'))

    op.drop_table('membership')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_status'))
        batch_op.drop_index(batch_op.f('ix_job_org_id'))
        batch_op.drop_index(batch_op.f('ix_job_name'))
        batch_op.drop_index('ix_job_claim')

    op.drop_table('job')
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitation_token_hash'))
        batch_op.drop_index(batch_op.f('ix_invitation_org_id'))

    op.drop_table('invitation')
    with op.batch_alter_table('glossary_v1_term', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glossary_v1_term_org_id'))

    op.drop_table('glossary_v1_term')
    with op.batch_alter_table('discussion_reaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_reaction_user_id'))
        batch_op.drop_index('ix_discussion_reaction_target')
        batch_op.drop_index(batch_op.f('ix_discussion_reaction_org_id'))

    op.drop_table('discussion_reaction')
    with op.batch_alter_table('discussion_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_group_org_id'))

    op.drop_table('discussion_group')
    with op.batch_alter_table('discussion_flag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_flag_org_id'))

    op.drop_table('discussion_flag')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_org_id'))

    op.drop_table('category')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_slug'))

    op.drop_table('organization')
    with op.batch_alter_table('installation_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installation_setting_key'))

    op.drop_table('installation_setting')
    # ### end Alembic commands ###
