"""Phase 6: newsletter subscribers and deliveries

Revision ID: 3ca747a71990
Revises: e46f0b314782
Create Date: 2026-08-25 02:18:43.354314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ca747a71990'
down_revision = 'e46f0b314782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_subscriber_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriber')),
    sa.UniqueConstraint('org_id', 'email', name='uq_subscriber_org_email')
    )
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriber_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriber_token'), ['token'], unique=True)

    op.create_table('newsletter_delivery',
    sa.Column('post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('recipients_total', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_newsletter_delivery_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_newsletter_delivery_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_newsletter_delivery_post_id_post'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_newsletter_delivery_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_delivery'))
    )
    with op.batch_alter_table('newsletter_delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_delivery_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_newsletter_delivery_post_id'), ['post_id'], unique=False)

    op.create_table('newsletter_delivery_recipient',
    sa.Column('delivery_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('subscriber_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['newsletter_delivery.id'], name=op.f('fk_newsletter_delivery_recipient_delivery_id_newsletter_delivery'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_newsletter_delivery_recipient_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscriber.id'], name=op.f('fk_newsletter_delivery_recipient_subscriber_id_subscriber'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_delivery_recipient')),
    sa.UniqueConstraint('delivery_id', 'subscriber_id', name='uq_delivery_recipient')
    )
    with op.batch_alter_table('newsletter_delivery_recipient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_delivery_recipient_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_newsletter_delivery_recipient_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_delivery_recipient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_delivery_recipient_org_id'))
        batch_op.drop_index(batch_op.f('ix_newsletter_delivery_recipient_delivery_id'))

    op.drop_table('newsletter_delivery_recipient')
    with op.batch_alter_table('newsletter_delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_delivery_post_id'))
        batch_op.drop_index(batch_op.f('ix_newsletter_delivery_org_id'))

    op.drop_table('newsletter_delivery')
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriber_token'))
        batch_op.drop_index(batch_op.f('ix_subscriber_org_id'))

    op.drop_table('subscriber')
    # ### end Alembic commands ###
