"""Phase 7: plugin ecosystem (org_plugin, glossary tables)

Revision ID: 639618c92013
Revises: 3ca747a71990
Create Date: 2026-08-25 02:24:22.983470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '639618c92013'
down_revision = '3ca747a71990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_v1_term',
    sa.Column('term', sa.String(length=100), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_glossary_v1_term_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_glossary_v1_term_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_glossary_v1_term_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary_v1_term')),
    sa.UniqueConstraint('org_id', 'term', name='uq_glossary_v1_term_org')
    )
    with op.batch_alter_table('glossary_v1_term', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glossary_v1_term_org_id'), ['org_id'], unique=False)

    op.create_table('org_plugin',
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('plugin_slug', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('upgraded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_org_plugin_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_plugin')),
    sa.UniqueConstraint('org_id', 'plugin_slug', name='uq_org_plugin')
    )
    with op.batch_alter_table('org_plugin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_plugin_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_plugin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_plugin_org_id'))

    op.drop_table('org_plugin')
    with op.batch_alter_table('glossary_v1_term', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glossary_v1_term_org_id'))

    op.drop_table('glossary_v1_term')
    # ### end Alembic commands ###
