"""Notification.emailed_at idempotency marker

Revision ID: aefb3d93b791
Revises: 1c7e4d3868a2
Create Date: 2026-08-25 10:11:36.210033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aefb3d93b791'
down_revision = '1c7e4d3868a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('emailed_at')

    # ### end Alembic commands ###
