"""Phase 2: pages, navigation, uploads, branding

Revision ID: b6f8a2bb0547
Revises: eb0dcc945f20
Create Date: 2026-08-25 01:42:49.480142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f8a2bb0547'
down_revision = 'eb0dcc945f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('template', sa.String(length=50), nullable=False),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.String(length=300), nullable=True),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_page_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_page_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_page_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page')),
    sa.UniqueConstraint('org_id', 'slug', name='uq_page_org_slug')
    )
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_page_org_status', ['org_id', 'status'], unique=False)

    op.create_table('upload',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('has_variants', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_upload_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_upload_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_upload_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload')),
    sa.UniqueConstraint('key', name=op.f('uq_upload_key'))
    )
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_org_id'), ['org_id'], unique=False)

    op.create_table('navigation_item',
    sa.Column('menu', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('page_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_navigation_item_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name=op.f('fk_navigation_item_page_id_page'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_navigation_item'))
    )
    with op.batch_alter_table('navigation_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_navigation_item_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_navigation_item_org_menu', ['org_id', 'menu', 'position'], unique=False)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_primary', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('brand_primary')

    with op.batch_alter_table('navigation_item', schema=None) as batch_op:
        batch_op.drop_index('ix_navigation_item_org_menu')
        batch_op.drop_index(batch_op.f('ix_navigation_item_org_id'))

    op.drop_table('navigation_item')
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_org_id'))

    op.drop_table('upload')
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_index('ix_page_org_status')
        batch_op.drop_index(batch_op.f('ix_page_org_id'))

    op.drop_table('page')
    # ### end Alembic commands ###
