"""Phase 8: custom domains

Revision ID: cd8b8dcb271f
Revises: 639618c92013
Create Date: 2026-08-25 02:29:19.727644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8b8dcb271f'
down_revision = '639618c92013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_domain',
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_org_domain_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_domain'))
    )
    with op.batch_alter_table('org_domain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_domain_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_org_domain_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_domain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_domain_org_id'))
        batch_op.drop_index(batch_op.f('ix_org_domain_domain'))

    op.drop_table('org_domain')
    # ### end Alembic commands ###
