"""Navigation dropdown groups (parent_id)

Revision ID: d6b85b1ec76a
Revises: cd8b8dcb271f
Create Date: 2026-08-25 09:06:17.811058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b85b1ec76a'
down_revision = 'cd8b8dcb271f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('navigation_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_navigation_item_parent_id_navigation_item'), 'navigation_item', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('navigation_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_navigation_item_parent_id_navigation_item'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
