"""Phase 5: discussions and notifications

Revision ID: e46f0b314782
Revises: 1c7d1abcf933
Create Date: 2026-08-25 02:13:13.433214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e46f0b314782'
down_revision = '1c7d1abcf933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_flag',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_discussion_flag_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_discussion_flag_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion_flag'))
    )
    with op.batch_alter_table('discussion_flag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_flag_org_id'), ['org_id'], unique=False)

    op.create_table('discussion_reaction',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_discussion_reaction_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_discussion_reaction_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion_reaction')),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', 'emoji', name='uq_discussion_reaction_user_target')
    )
    with op.batch_alter_table('discussion_reaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_reaction_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_discussion_reaction_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_reaction_user_id'), ['user_id'], unique=False)

    op.create_table('discussion_space',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_discussion_space_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion_space')),
    sa.UniqueConstraint('org_id', 'slug', name='uq_discussion_space_org_slug')
    )
    with op.batch_alter_table('discussion_space', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_space_org_id'), ['org_id'], unique=False)

    op.create_table('notification',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_notification_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notification_user_read', ['user_id', 'read_at'], unique=False)

    op.create_table('discussion_topic',
    sa.Column('space_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_discussion_topic_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_discussion_topic_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['discussion_space.id'], name=op.f('fk_discussion_topic_space_id_discussion_space'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_discussion_topic_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion_topic'))
    )
    with op.batch_alter_table('discussion_topic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_topic_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_discussion_topic_space_activity', ['space_id', 'last_activity_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_topic_space_id'), ['space_id'], unique=False)

    op.create_table('discussion_follow',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('topic_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_discussion_follow_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['discussion_topic.id'], name=op.f('fk_discussion_follow_topic_id_discussion_topic'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_discussion_follow_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion_follow')),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_discussion_follow_user_topic')
    )
    with op.batch_alter_table('discussion_follow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_follow_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_follow_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_follow_user_id'), ['user_id'], unique=False)

    op.create_table('discussion_reply',
    sa.Column('topic_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_discussion_reply_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_discussion_reply_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['discussion_reply.id'], name=op.f('fk_discussion_reply_parent_id_discussion_reply'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['discussion_topic.id'], name=op.f('fk_discussion_reply_topic_id_discussion_topic'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_discussion_reply_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion_reply'))
    )
    with op.batch_alter_table('discussion_reply', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_reply_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_reply_topic_id'), ['topic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion_reply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_reply_topic_id'))
        batch_op.drop_index(batch_op.f('ix_discussion_reply_org_id'))

    op.drop_table('discussion_reply')
    with op.batch_alter_table('discussion_follow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_follow_user_id'))
        batch_op.drop_index(batch_op.f('ix_discussion_follow_topic_id'))
        batch_op.drop_index(batch_op.f('ix_discussion_follow_org_id'))

    op.drop_table('discussion_follow')
    with op.batch_alter_table('discussion_topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_topic_space_id'))
        batch_op.drop_index('ix_discussion_topic_space_activity')
        batch_op.drop_index(batch_op.f('ix_discussion_topic_org_id'))

    op.drop_table('discussion_topic')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_user_read')
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_org_id'))

    op.drop_table('notification')
    with op.batch_alter_table('discussion_space', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_space_org_id'))

    op.drop_table('discussion_space')
    with op.batch_alter_table('discussion_reaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_reaction_user_id'))
        batch_op.drop_index('ix_discussion_reaction_target')
        batch_op.drop_index(batch_op.f('ix_discussion_reaction_org_id'))

    op.drop_table('discussion_reaction')
    with op.batch_alter_table('discussion_flag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_flag_org_id'))

    op.drop_table('discussion_flag')
    # ### end Alembic commands ###
